version: 2

models:
  - name: stg_customers
    description: Detailed info about customers
    columns: 
    - name: customer_id
      description: '{{ doc("primary_key")}}'
      tests:
        - unique
        - not_null
  - name: stg_nations
    columns: 
    - name: nation_id
      tests:
        - unique
        - not_null
    - name: region_id
      test: 
        - relationships:
            to: ref('stg_regions')
            field: region_id
            config: 
              store_failures: true
  - name: stg_regions
    columns: 
    - name: region_id
      tests:
        - unique
        - not_null
    - name: name
      tests:
        - accepted_values:
           values: ['ASIA','AFRICA','AMERICA','EUROPE','MIDDLE EAST']